trigger:
  - master

pool:
  vmImage: 'windows-2019'

variables:
  BuildConfiguration: 'Release'
  ServiceConnection: 'Jason Specland MS Internal (78665f33-bc7d-43df-9f83-ac1064dd74eb)'

stages:
- stage: 'Build'
  jobs:
  - job:
    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        zipAfterPublish: True

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
      condition: succeededOrFailed()

- stage: 'Deploy'
  jobs:
  - deployment: 'Deploy'
    environment: 'Dev'
    variables:
      EnvironmentName: 'Development'
      MyVariable: 'DEV_VALUE'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy Azure App Service'
            inputs:
              azureSubscription: '$(ServiceConnection)'
              appType: 'webApp'
              WebAppName: 'pipelinesapprovaldemo-dev'
              package: '$(Pipeline.Workspace)/**/*.zip'
              AppSettings: '-ASPNETCORE_ENVIRONMENT $(EnvironmentName) -MyVariable $(MyVariable)'


