name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  BuildConfiguration: 'Release'

stages:
- stage: 'Build'
  jobs:
  - job: 'Build'
    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        zipAfterPublish: True

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
